---
title: "Jun Sample Tiers and Plant IDs"
author: "sjr267"
date: "2024-02-28"
output: html_document
---

```{r load packages and set label parameters}
library(config)
library(RMariaDB)
library(tidyverse)
```

```{r dbconnect}
# Connect to the VSL database, which lives on Zeus
vsl <- config::get("VSL_database")

con <- dbConnect(RMariaDB::MariaDB(),
                 dbname = vsl$dbname,
                 host = vsl$host,
                 port = vsl$port,
                 user = vsl$user,
                 password = vsl$password)
```

```{r}
train <- read.csv("train_data_with_DI.csv", header = TRUE) %>%
  separate_wider_delim(cols = SampleID, "-", names = c("before", "after"), names_sep = "_", too_few = "align_start") %>%
  rowwise() %>%
  mutate(
    actual_before = case_when(
      is.na(SampleID_after) ~ SampleID_before,
      SampleID_after == "Nov" ~ "11",
      SampleID_after == "Dec" ~ "12",
      TRUE ~ SampleID_before
    ),
    actual_after = case_when(
      is.na(SampleID_after) ~ NA,
      SampleID_after %in% c("Nov", "Dec") ~ SampleID_before,
      TRUE ~ SampleID_after
    ),
    .keep = "unused"
  ) %>%
  unite(col = "SampleID_real", c("actual_before", "actual_after"), sep = "-", remove = TRUE, na.rm = TRUE) %>%
  rowwise() %>%
  mutate(
    tier = dbGetQuery(con, paste0("SELECT tier FROM (plants LEFT JOIN samples ON plants.ID = samples.plantID) LEFT JOIN projects ON samples.projectNumber = projects.ID WHERE sampleID = '", SampleID_real, "' AND projects.projectNumber = ", VSLNumber, ";"))[1, 1],
    plantID = dbGetQuery(con, paste0("SELECT plants.ID FROM (plants LEFT JOIN samples ON plants.ID = samples.plantID) LEFT JOIN projects ON samples.projectNumber = projects.ID WHERE sampleID = '", SampleID_real, "' AND projects.projectNumber = ", VSLNumber, ";"))[1, 1]
  ) %>%
  relocate(plantID, tier, SampleID_real, .after = "VSLNumber")

write.csv(train, file = "train_data_tier_plant.csv")

test <- read.csv("test_data_with_DI_new.csv", header = TRUE) %>%
  separate_wider_delim(cols = SampleID, "-", names = c("before", "after"), names_sep = "_", too_few = "align_start") %>%
  rowwise() %>%
  mutate(
    actual_before = case_when(
      SampleID_after == "Nov" ~ "11",
      SampleID_after == "Dec" ~ "12",
      SampleID_after == "Feb" ~ "02",
      SampleID_before %in% 1:5 ~ paste0("0", SampleID_before),
      is.na(SampleID_after) ~ SampleID_before,
      TRUE ~ SampleID_before
    ),
    actual_after = case_when(
      SampleID_after %in% c("Nov", "Dec", "Feb") ~ SampleID_before,
      is.numeric(SampleID_after) ~ SampleID_after,
      is.na(SampleID_after) ~ NA,
      TRUE ~ NA
    ),
    .keep = "unused"
  ) %>%
  unite(col = "SampleID_real", c("actual_before", "actual_after"), sep = "-", remove = TRUE, na.rm = TRUE) %>%
  rowwise() %>%
  mutate(
    tier = dbGetQuery(con, paste0("SELECT tier FROM (plants LEFT JOIN samples ON plants.ID = samples.plantID) LEFT JOIN projects ON samples.projectNumber = projects.ID WHERE sampleID = '", SampleID_real, "' AND projects.projectNumber = ", VSLNumber, ";"))[1, 1],
    plantID = dbGetQuery(con, paste0("SELECT plants.ID FROM (plants LEFT JOIN samples ON plants.ID = samples.plantID) LEFT JOIN projects ON samples.projectNumber = projects.ID WHERE sampleID = '", SampleID_real, "' AND projects.projectNumber = ", VSLNumber, ";"))[1, 1]
  ) %>%
  relocate(plantID, tier, SampleID_real, .after = "VSLNumber")

write.csv(train, file = "test_data_tier_plant.csv")
```

```{r disconnect}
dbDisconnect(con)
```